#!/usr/bin/env zsh

### ALIASES ###
# Default modifiers
alias clear='printf "\033c"'
alias cower='cower --color auto'
alias df='df -h'
alias du='du -h'
alias free='free -h'
alias iotop='sudo iotop -o'
alias pdflatex='pdflatex -halt-on-error'
alias pgrep='pgrep -fl'
alias shred='shred -uv'
alias sudo='sudo -E'
alias valgrind='valgrind --track-origins=yes'
alias vi='vim'
alias view='vim -Rp'
alias vim='vim -p'
alias which='which -a'
alias youtube-dl='noglob youtube-dl -o \%\(title\)s.\%\(ext\)s'
alias xsnow='xsnow -nokeepsnow -notrees'

# Modifiers on file operations
# * Verbosity so you know what's going on
# * Prevent rm from removing file systems
# * Prevent chmod from operating on /
alias chmod='chmod -v --preserve-root'
alias cp='cp -v'
alias ln='ln -v'
alias mv='mv -v'
alias rm='rm -v --one-file-system'

# Disabled commands
alias dm-tool='command-disabled'

# Colorize output
alias diff='colordiff'
alias grep='grep --color'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias ls='ls -hHF --color=tty'
alias less='less -r'

# Derivative commands
alias cpa='cp -a'
alias la='ls -A'
alias latr='ls -Altr'
alias ll='ls -l'
alias lla='ls -Al'
alias ltr='ls -ltr'

# Shortcut commands
alias allgrp='cut -d: -f1 /etc/group'
alias allusr='cut -d: -f1 /etc/passwd'
alias checkip='curl ifconfig.me'
alias define='sdcv'
alias doc2pdf='libreoffice --headless --invisible --norestore --convert-to pdf'
alias dtail='dmesg | tail'
alias jctl='journalctl'
alias keyart='ssh-keygen -lv -f'
alias lsnet='ls /sys/class/net'
alias open='xdg-open'
alias sctl='sudo -E systemctl'
alias srcrc='source ~/.zshrc'
alias sshagent='eval $(ssh-agent -t 15m)'
alias vigtk='sudo vi -p /usr/share/gtk-2.0/gtkrc /usr/share/gtk-3.0/settings.ini'
alias vii3='vim ~/.config/i3/config'
alias virc='vim -p ~/.zshrc ~/.zshrc.d/*'
alias week='date +%V'
alias ytmp3='noglob youtube-dl -o %\(title\)s.%\(ext\)s --extract-audio'

# gcalcli shortcuts
alias calm='gcalcli calm'
alias calw='gcalcli calw'
alias agenda='gcalcli agenda'
alias gadd='gcalcli add --calendar "grawcards@gmail.com"'

# File navigation commands
alias largest="find . -printf '%s %p\n' | sort -nr | head"
alias smallest="find . -printf '%s %p\n' | sort -nr | tail"

# Script shortcuts
alias mkdesktop='/usr/local/scripts/mkdesktop.sh'

# For fun
alias chanstamp='date +%s%3N'
alias maze='Z=╱╲;for((;;)){ printf ${Z:RANDOM&1:1};sleep .01;};unset Z'
alias mpvnc='mpv --speed=1.5 --audio-pitch-correction=no --no-video'
alias mpvac='mpv --speed=0.67 --audio-pitch-correction=no --no-video'

### FUNCTIONS ###
# Shortcut commands
cdls() { cd "$@" && ls; }
cdmv() { mv "$1" "$2" && cd "$2"; }
catls() { [ -d "$1" ] && ls "$1" || cat "$1"; }
countf() { /usr/bin/ls -1 $@ | wc -l; }
digq() { dig "$@" | grep 'Query time'; }
lsicon() { ls /usr/share/icons/Numix-Circle/scalable/apps | grep "$1"; }
mkcd() { mkdir -p "$@" && cd "$@"; }
pacbin() { pacman -Ql "$1" | grep --color=never bin; }
pexec() { echo $@; $@; }
pls() { sudo -- "${SHELL:-zsh}" -c "$(fc -ln -1)"; }
strerror() { python -c "import os; print(os.strerror($1))"; }
trash() { [ $# -eq 0 ] && trash-list || trash-put $@; }

# Colorize text
red()    { printf "\e[31m\e[1m"$@"\e[0m"; }
green()  { printf "\e[32m\e[1m"$@"\e[0m"; }
blue()   { printf "\e[34m\e[1m"$@"\e[0m"; }
redl()   { printf "\e[31m"$@"\e[0m"; }
greenl() { printf "\e[32m"$@"\e[0m"; }
bluel()  { printf "\e[34m"$@"\e[0m"; }

# Hash checkers
md5check() { test `md5sum $2 | cut -d' ' -f1` == "$1" && green '[OK]' || red '[FAIL]'; }
sha1check() { test `sha1sum $2 | cut -d' ' -f1` == "$1" && green '[OK]' || red '[FAIL]'; }
sha256check() { test `sha256sum $2 | cut -d' ' -f1` == "$1" && green '[OK]' || red '[FAIL]'; }

