#!/usr/bin/env zsh

# 256 colors please
if [[ "$TERM" == xterm ]]; then
    export TERM=xterm-256color
fi

# Set the home/end keys
bindkey "${terminfo[khome]}" beginning-of-line
bindkey "${terminfo[kend]}" end-of-line

which fzf > /dev/null || bindkey '^R' history-incremental-search-backward

# Makes bpython the default interactive shell
python()  { [[ $# -eq 0 ]] && bpython  || env python  "$@"; }
python2() { [[ $# -eq 0 ]] && bpython2 || env python2 "$@"; }

if [[ "$EUID" -eq 0 ]]; then
    case "$(uname)" in
        Darwin)
            alias ls='ls -AGF'
            ;;
        Linux)
            alias ls='ls -AhHF --color=tty'
            ;;
    esac
fi

# Allow GPG signing over SSH
export GPG_TTY="$(tty)"
[[ -n "$SSH_CONNECTION" ]] && export PINENTRY_USER_DATA='USE_CURSES=1'

