#!/usr/bin/env bash

# General options
panel_fifo="/tmp/${USER}_lemonbar_fifo"

# Alarm settings
cpu_alert=70
mem_alert=50
net_alert=10

# Update delay
update_mus=10

# Color definitions in #aarrggbb format
bg_color="#1a1a1a"
fg_color="#cccccc"
color_head="#000066"
color_sec_b1="#004d00"
color_sec_b2="#4d0026"
color_sec_b3="#55552b"
color_wsp="#003300"
color_cpu="#e67300"
color_mem="${color_cpu}"
color_disabled="#1d1f21"

# Special characters
sep_left=""
sep_right=""
sepl_left=""
sepl_right=""

