#!/usr/bin/env bash

source $(dirname $0)/config

if [ $(pgrep -cx $(basename $0)) -gt 1 ]; then
    echo "The status bar is already running." >&2
    exit 1
fi

[[ ! -p ${panel_fifo} ]] && mkfifo -m 600 ${panel_fifo}

windowtitle() {
    xdotool getactivewindow getwindowname 2> /dev/null | sed -n 1p | cut -c 1-50
}

volume() {
    printf '%d%%' "$(pamixer --get-volume)"
    #amixer -D pulse get Master | grep % | sed -n 1p | awk -F '[' '{print $2}' | awk -F ']' '{print $1}'
}

music() {
    /usr/local/scripts/wm/media/nowplaying.sh
}

main() {
    local count_mus=${update_mus}

    conky -c "$(dirname $0)/conky" &

    while true; do
        echo "VOL$(volume)"
        echo "MUS$(music)"
        echo "WIN$(windowtitle)"

        if [ $((count_mus++)) -ge ${update_mus} ]; then
            echo "$(music)"
            count_mus=0
        fi

        sleep 1
    done
}

main > "${panel_fifo}" &

cat "${panel_fifo}" \
    | "$(dirname $0)/parser" \
    | lemonbar -p -f "${font}" -f "${iconfont}" -B "${bg_color}" -F "${fg_color}"
wait

