#!/usr/bin/env bash

# General options
panel_fifo="/tmp/${USER}_lemonbar_fifo"
font='-xos4-terminesspowerline-medium-r-normal--12-120-72-72-c-60-iso10646-1'
iconfont='-xos4-terminusicons2mono-medium-r-normal--12-120-72-72-m-60-iso8859-1'

# Alarm settings
cpu_alert=70
mem_alert=50
net_alert=10

# Update delay
update_mus=10

# Color definitions in #aarrggbb or #rrggbb format
color_back='#ff000000'
color_fore='#ffcccccc'
color_active_wsp='#ff002db3'
color_other_wsp='#ff000000'
color_alert='#ffe67300'
color_disabled='#ff000099'

# Special characters
sep_left=''
sep_right=''
sepl_left=''
sepl_right=''
up_arrow=''
down_arrow=''
up_caret=''
down_caret=''
icon_question=''
icon_media_play=''
icon_media_pause=''
icon_wifi=''
icon_bluetooth=''
icon_linux=''

# Icon glyphs from Terminusicons2 (wip)
icon_clock='Õ'                      # Clock icon
icon_cpu='Ï'                        # CPU icon
icon_mem='Þ'                        # MEM icon
icon_dl='Ð'                         # Download icon
icon_ul='Ñ'                         # Upload icon
icon_vol='Ô'                        # Volume icon
icon_hd='À'                         # HD / icon
icon_home='Æ'                       # HD /home icon
icon_mail='Ó'                       # Mail icon
icon_chat='Ò'                       # IRC/Chat icon
icon_music='Î'                      # Music icon
icon_prog='Â'                       # Window icon
icon_contact='Á'                    # Contact icon
icon_wsp='É'                        # Workspace icon

