#!/usr/bin/env bash

source "$(dirname $0)/config"

# Parser main loop
while read -r line; do
    case "${line}" in
        SYS*)
            # Conky output:
            # 0 - Weekday
            # 1 - Month
            # 2 - Day of month
            # 3 - Year
            # 4 - Time
            # 5 - AM/PM
            # 6 - CPU
            # 7 - Memory
            # 8 - Internet download
            # 9 - Internet upload
            arr=(${line#???})

            # Date and time
            date="${sep_left} ${arr[0]} ${arr[1]} ${arr[2]} ${arr[3]} ${arr[4]} ${arr[5]}"

            # CPU
            if [ ${arr[6]::-1} -gt ${cpu_alert} ]; then
                cpu_back="${color_alert}"
                cpu_fore="${color_back}"
            else
                cpu_back="${color_back}"
                cpu_fore="${color_fore}"
            fi
            cpu="%{F${cpu_back}}${sep_left}%{F${cpu_fore} B${cpu_back}} CPU: ${arr[6]}"

            # Memory
            if [ ${arr[7]::-1} -gt ${mem_alert} ]; then
                mem_back="${color_alert}"
                mem_fore="${color_back}"
            else
                mem_back="${color_back}"
                mem_fore="${color_fore}"
            fi
            mem="%{F${mem_back}}${sepl_left}%{F${mem_fore} B${mem_back}} MEM: ${arr[7]}"

            # Network
            net_back="${color_back}"
            net_fore="${color_fore}"

            netu="%{F${net_back}}${sepl_left}%{F${net_fore} B${net_back}} ${arr[9]}"
            netd="%{F${net_back}}${sepl_left}%{F${net_fore} B${net_back}} ${arr[8]}"
            net="NET: ${netu} /${netd}"
            ;;
        WIN*)
            title="${line:3}"
            ;;
    esac

    wsp="%{B${color_active_wsp}}[1]%{F${color_active_wsp} B${color_back}}${sep_right}%{B${color_back} F${color_fore}}"
    # Finally, output
    #echo "%{l}${wsp}%{c}${title}%{r} ${cpu} ${mem} ${net} ${date}"
    echo "%{l}${wsp}%{c}${title}%{r} stuff"
done

