[bell]
animation = "EaseOutExpo"
duration = 0

[colors.bright]
black = "#282a2e"
blue = "#81a2be"
cyan = "#8abeb7"
green = "#b5bd68"
magenta = "#b294bb"
red = "#cc6666"
white = "#c5c8c6"
yellow = "#f0c674"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#1d1f21"
blue = "#5c7387"
cyan = "#5e8d87"
green = "#8c9440"
magenta = "#85678f"
red = "#a54242"
white = "#8e8e8e"
yellow = "#dea95f"

[colors.primary]
background = "#151428"
foreground = "#949494"

[font]
size = 11.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"
